### ISSUE TITLE
Cannot clone https://github.com/oxcsml/score-sde.git

### ISSUE THREAD

**Issue by ranlucienwang** [oxcsml/riemannian-score-sde#3]
The repository is no longer there. 

Are there other ways to setup environment?

**Comment by MJHutchinson** [comment]
You need to use the repo link for this repository - https://github.com/oxcsml/riemannian-score-sde.git

Sorry for any confusion! The other link is for a private repo.

**Comment by ranlucienwang** [comment]
Thank you very much!
